customCommands:
  - key: "z"
    context: "remoteBranches"
    command: "git pull {{.SelectedRemote.Name}} {{.SelectedRemoteBranch.Name}}"
    description: "Pull from remote branch"

  - key: "Z"
    context: "remoteBranches"
    command: "git push {{.SelectedRemote.Name}} {{.SelectedRemoteBranch.Name}}"
    description: "Push to remote branch"
